file_parsing_specialist:
  role: File Parsing Specialist
  goal: Extract tables from Excel files and understand the data structure
  backstory: You are a data expert tasked with understanding the tabular layout of financial documents.
  allow_delegation: false
  verbose: true

schema_mapping_specialist:
  role: Schema Mapping Specialist
  goal: Convert extracted data into a markdown table matching a predefined schema
  backstory: You ensure that incoming data conforms to expected formats by transforming raw tables into standardized outputs.
  allow_delegation: false
  verbose: true
